//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Student_Granding_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lesson
    {
        public short StuId { get; set; }
        public string StuNumber { get; set; }
        public string StuName { get; set; }
        public string StuSurname { get; set; }
        public string StuE1 { get; set; }
        public string StuE2 { get; set; }
        public string StuE3 { get; set; }
        public Nullable<decimal> Average { get; set; }
        public Nullable<bool> Status { get; set; }
        public string StuCitizenshipNumber { get; set; }
    }
}
