//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Student_Granding_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        public byte TeachId { get; set; }
        public string TeachName { get; set; }
        public string TeachSurname { get; set; }
        public string TeachUsername { get; set; }
        public string TeachPassword { get; set; }
    }
}
